env:
  browser: true
  es2021: true
  node: true
settings:
  react:
    version: 18.2.0
  import/parsers:
    "@typescript-eslint/parser": [".ts", ".tsx"]
  import/resolver:
    typescript:
      project: 'tsconfig.json'
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
  - import
rules:
  import/order: 2
